spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://112.74.178.136:3306/selldb?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html

    mode: HTML5
    cache: false
mybatis:
  type-aliases-package: com.ncvt.medicawebdao.dao
  mapper-locations: classpath*:mapper/*.xml

